WebApplication/ViewModels/CpuViewModel.cs
using Models.Product;

namespace WebApplication.ViewModels
{
    public class CpuViewModel : BaseProductViewModel<Cpu>
    {
    }
}

WebApplication/ViewModels/InfoViewModel.cs
using System.Collections.Generic;

namespace WebApplication.ViewModels
{
    public class InfoViewModel<TProduct>
    {
        public TProduct Product { get; set; }
        public List<TProduct> PopularGoods { get; set; }
    }
}

WebApplication/Controllers/CpuController.cs
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using DataProvider.Interfaces;
using Logic.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Models.Product;
using WebApplication.Interfaces.FiltersContracts;
using WebApplication.Interfaces.SortContracts;
using WebApplication.ViewModels;
using WebApplication.ViewModels.AddViewModels;
using WebApplication.ViewModels.FilterViewModels;

namespace WebApplication.Controllers
{
    public class CpuController : Controller
    {
        private const int PageSize = 20;

        private readonly ICpuFilter _cpuFilter;
        private readonly ICpuRepository _cpuRepository;
        private readonly ICpuSortService _cpuSortService;
        private readonly IRepositoryWrapper _repositoryWrapper;
        private readonly IFileService _fileService;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public CpuController(IRepositoryWrapper repositoryWrapper, ISortServiceWrapper sortServiceWrapper,
            ICpuFilter cpuFilter, IFileService fileService, IWebHostEnvironment webHostEnvironment)
        {
            _repositoryWrapper = repositoryWrapper;
            _cpuFilter = cpuFilter;
            _fileService = fileService;
            _webHostEnvironment = webHostEnvironment;
            _cpuRepository = _repositoryWrapper.CpuRepository;
            _cpuSortService = sortServiceWrapper.CpuSortService;
        }


        public IActionResult Index(int page = 1, string name = null,
            SortState sortState = SortState.DateAddedDesc,
            string manufacturer = BaseFilterViewModel.AllManufacturers)
        {
            var viewModel = PrepareData(page, name, sortState, manufacturer);
            return View(viewModel.Result);
        }

        [Authorize(Roles = "admin")]
        public IActionResult Table(int page = 1, string name = null,
            SortState sortState = SortState.DateAddedDesc,
            string manufacturer = BaseFilterViewModel.AllManufacturers)
        {
            var viewModel = PrepareData(page, name, sortState, manufacturer);
            return View(viewModel.Result);
        }

        public IActionResult Info(Guid id)
        {
            var product = _cpuRepository.FindByCondition(x => x.Product.Id == id).First();

            var infoViewModel = new InfoViewModel<Cpu>
            {
                Product = product,
                PopularGoods = _cpuRepository.FindAll()
                    .OrderByDescending(x => x.Product.DateAdded)
                    .Take(4).ToList()
            };

            return View(infoViewModel);
        }

        [Authorize(Roles = "admin")]
        public IActionResult Remove(Guid id)
        {
            var product = _cpuRepository.FindByCondition(x => x.Id == id).FirstOrDefault();

            if (product == null) return RedirectToAction("Table");

            _fileService.DeleteFile(_webHostEnvironment.WebRootPath + product.Product.ImageUrl);
            _cpuRepository.Delete(product);
            _repositoryWrapper.Save();

            return RedirectToAction("Table");
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public IActionResult Add()
        {
            return View();
        }

        public IActionResult Add(AddCpuViewModel cpuViewModel)
        {
            var guid = Guid.NewGuid();
            string filePath;

            if (cpuViewModel.UploadedFile != null)
            {
                var fileExtension = Path.GetExtension(cpuViewModel.UploadedFile.FileName);
                var fileName = Path.GetFileNameWithoutExtension(cpuViewModel.UploadedFile.FileName);
                filePath = "/productsImages/Cpu/" + fileName + guid + fileExtension;
                _fileService.SaveUploadedFile(cpuViewModel.UploadedFile, _webHostEnvironment.WebRootPath + filePath);
            }
            else
            {
                filePath = "/productsImages/default.jpg";
            }

            var cpu = new Cpu
            {
                Id = guid,
                BaseClock = cpuViewModel.BaseClock,
                L2Cache = cpuViewModel.L2Cache,
                L3Cache = cpuViewModel.L2Cache,
                MaxMemoryFrequency = cpuViewModel.MaxMemoryFrequency,
                MaximumFrequency = cpuViewModel.MaximumFrequency,
                MaximumNumberThreads = cpuViewModel.MaximumNumberThreads,
                NumberCores = cpuViewModel.NumberCores,
                NumberMemoryChannels = cpuViewModel.NumberMemoryChannels,
                Socket = cpuViewModel.Socket,
                MemorySupport = cpuViewModel.MemorySupport,
                SocketTypeId = 1,
                Tdp = cpuViewModel.Tdp,
                Product = new Product
                {
                    Id = guid,
                    CategoryId = 2,
                    Name = cpuViewModel.Name,
                    ImageUrl = filePath,
                    DateAdded = DateTime.Now,
                    Price = cpuViewModel.Price,
                    QuantityInStock = cpuViewModel.QuantityInStock,
                    ManufacturerId = 1
                }
            };

            _cpuRepository.Create(cpu);
            _repositoryWrapper.Save();

            return View();
        }

        private async Task<CpuViewModel> PrepareData(int page = 1, string name = null,
            SortState sortState = SortState.DateAddedDesc,
            string manufacturer = BaseFilterViewModel.AllManufacturers)
        {
            var products = _cpuRepository.FindAll();
            var manufacturers = products.Select(x => x.Product.Manufacturer.Name).Distinct();

            var filterViewModel = new BaseFilterViewModel(manufacturers.ToList(), manufacturer);

            if (name != null) products = products.Where(x => x.Product.Name.Contains(name));

            products = _cpuFilter.ApplyBaseFilter(filterViewModel, products);

            products = _cpuSortService.SortBy(sortState, products);

            var count = await products.CountAsync();

            var items = await products.Skip((page - 1) * PageSize).Take(PageSize).ToListAsync();

            var pageViewModel = new PageViewModel(count, page, PageSize);

            var cpuViewModel = new CpuViewModel
            {
                BaseFilterViewModel = filterViewModel,
                SortBaseViewModel = new SortBaseViewModel(sortState),
                Products = items,
                PageViewModel = pageViewModel,
                NewItems = products
                    .OrderByDescending(x => x.Product.DateAdded)
                    .Take(20).ToList()
            };
            return cpuViewModel;
        }
    }
}

WebApplication/Views/Cpu/Add.cshtml
@model WebApplication.ViewModels.AddViewModels.AddCpuViewModel

@{
    ViewData["Title"] = "Add";
    Layout = "_AdminPanel";
}

    <form asp-action="Add" asp-controller="Cpu" method="post" enctype="multipart/form-data" style="padding-top: 100px; width: 50%; margin: auto;">
        <div class="file-upload">
            <button class="file-upload-btn" type="button" onclick="$('.file-upload-input').trigger( 'click' )">Add Image</button>

            <div class="image-upload-wrap">
                <input class="file-upload-input" asp-for="UploadedFile" type='file' onchange="readURL(this);" accept="image/*" />
                <div class="drag-text">
                    <h3>Drag and drop a file or select add Image</h3>
                </div>
            </div>
            <div class="file-upload-content">
                <img class="file-upload-image" src="#" alt="your image" />
                <div class="image-title-wrap">
                    <button type="button" onclick="removeUpload()" class="remove-image">Remove <span class="image-title">Uploaded Image</span></button>
                </div>
            </div>
        </div>
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Socket" class="control-label"></label>
            <input asp-for="Socket" class="form-control" />
            <span asp-validation-for="Socket" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="NumberCores" class="control-label"></label>
            <input asp-for="NumberCores" class="form-control" />
            <span asp-validation-for="NumberCores" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="MaximumNumberThreads" class="control-label"></label>
            <input asp-for="MaximumNumberThreads" class="form-control" />
            <span asp-validation-for="MaximumNumberThreads" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="BaseClock" class="control-label"></label>
            <input asp-for="BaseClock" class="form-control" />
            <span asp-validation-for="BaseClock" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="MaximumFrequency" class="control-label"></label>
            <input asp-for="MaximumFrequency" class="form-control" />
            <span asp-validation-for="MaximumFrequency" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="L2Cache" class="control-label"></label>
            <input asp-for="L2Cache" class="form-control" />
            <span asp-validation-for="L2Cache" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="L3Cache" class="control-label"></label>
            <input asp-for="L3Cache" class="form-control" />
            <span asp-validation-for="L3Cache" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="MemorySupport" class="control-label"></label>
            <input asp-for="MemorySupport" class="form-control" />
            <span asp-validation-for="MemorySupport" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="NumberMemoryChannels" class="control-label"></label>
            <input asp-for="NumberMemoryChannels" class="form-control" />
            <span asp-validation-for="NumberMemoryChannels" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="MaxMemoryFrequency" class="control-label"></label>
            <input asp-for="MaxMemoryFrequency" class="form-control" />
            <span asp-validation-for="MaxMemoryFrequency" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Tdp" class="control-label"></label>
            <input asp-for="Tdp" class="form-control" />
            <span asp-validation-for="Tdp" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Name" class="control-label"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Price" class="control-label"></label>
            <input asp-for="Price" class="form-control" />
            <span asp-validation-for="Price" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="QuantityInStock" class="control-label"></label>
            <input asp-for="QuantityInStock" class="form-control" />
            <span asp-validation-for="QuantityInStock" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="submit" value="Create" class="btn btn-primary" />
        </div>

    </form>

WebApplication/Views/Cpu/Info.cshtml
@model WebApplication.ViewModels.InfoViewModel<Cpu>
@{
    ViewData["Title"] = "Info";
    Layout = "_StartPage";
}

    <div class="container dark-grey-text mt-5">

        <!--Grid row-->
        <div class="row wow fadeIn">

            <!--Grid column-->
            <div class="col-md-6 mb-4" style="margin: auto; text-align: center;">
              
                <img src="@Model.Product.Product.ImageUrl" class="img-fluid w-75" alt="">

            </div>
            <!--Grid column-->
            <!--Grid column-->
            <div class="col-md-6 mb-4">

                <!--Content-->
                <div class="p-4">

                    <div class="mb-3">
                        <a href="">
                            <span class="badge purple mr-1">@Model.Product.Product.Category.Name</span>
                        </a>
                        <a href="">
                            <span class="badge blue mr-1">New</span>
                        </a>
                    </div>

                    <p class="lead">
                        <span>$@Model.Product.Product.Price</span>
                    </p>

                    <p class="lead font-weight-bold">@Model.Product.Product.Name</p>

                    <p>
                        Производитель: @Model.Product.Product.Manufacturer.Name
                    </p>
                    <p>
                        Дата выхода на рынок: @Model.Product.Product.DateAdded
                    </p>
                    <p>
                        @if (Model.Product.Product.IsIndicatedRating())
                        {

                            <i class="far fa-star" style="padding: 5px 5px; margin: 5px 0px;" title="Количество голосов: @Model.Product.Product.NumberOfRatings()">@Math.Round(Model.Product.Product.GetAverageRating(), 1)</i>
                        }
                        else
                        {
                            <i class="far fa-star p-1" style="padding: 5px 5px; margin: 5px 0px;" title="Количество голосов: 0">?</i>
                        }

                        <i class="far fa-comment p-1 m-1" style="padding: 5px 5px; margin: 5px 0px;" title="Количество отзывов">@Model.Product.Product.GetCountReviews()</i>

                    </p>

                    <p>
                        <form class="d-flex justify-content-left">
                            <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
                            <button class="btn btn-red  btn-md my-0 p" type="submit">
                                Add to cart
                                <i class="fas fa-shopping-cart ml-1"></i>
                            </button>
                        </form>
                    </p>


                    @if (User.Identity.IsAuthenticated)
                    {
                        @if (Model.Product.Product.Ratings.All(x => x.User.UserName != User.Identity.Name))
                        {
                            <p>
                                <form class="d-flex justify-content-left" asp-controller="ProductGeneral" asp-action="Rate">
                                    <input type="number" min="1" max="10" value="1" aria-label="Search" name="rating" class="form-control" style="width: 100px" />
                                    <input type="hidden" value="@Model.Product.Id" name="id" />
                                    <button class="btn btn-primary btn-md my-0 p" type="submit">
                                        Поставить оценку
                                    </button>
                                </form>
                            </p>
                        }
                        else
                        {
                            <p>
                                <form class="d-flex justify-content-left" asp-controller="ProductGeneral" asp-action="ChangeRating">
                                    <input type="number" min="1" max="10"
                                           value="@Model.Product.Product.Ratings.FirstOrDefault(x => x.User.UserName == User.Identity.Name)?.Value"
                                           aria-label="Search" name="rating" class="form-control" style="width: 100px" />
                                    <input type="hidden" value="@Model.Product.Id" name="id" />
                                    <button class="btn btn-primary btn-md my-0 p" type="submit">
                                        Изменить оценку
                                    </button>
                                </form>
                            </p>
                        }

                    }

                    @if (User.Identity.IsAuthenticated)
                    {
                        <button class="btn btn-deep-orange  btn-md my-0 p addToFavorite" id="@Model.Product.Id" type="submit">
                            Добавить в избранное<i class="far fa-thumbs-up ml-1"></i>
                        </button>
                       
                    }

                </div>
                <!--Content-->

            </div>
            <!--Grid column-->

        </div>
        <!--Grid row-->

        <hr>
        <p class="lead font-weight-bold">Технические характеристики</p>
        <table class="table table-hover">
            <tbody>
                <tr>
                    <th scope="row">1</th>
                    <td>Сокет</td>
                    <td>@Model.Product.Socket</td>

                </tr>
                <tr>
                    <th scope="row">2</th>
                    <td>Количество ядер</td>
                    <td>@Model.Product.NumberCores</td>

                </tr>
                <tr>
                    <th scope="row">3</th>
                    <td>Максимальное количество потоков</td>
                    <td>@Model.Product.MaximumNumberThreads</td>
                </tr>
                <tr>
                    <th scope="row">4</th>
                    <td>Базовая тактовая частота</td>
                    <td>@Math.Round(Model.Product.BaseClock, 2) Гц</td>
                </tr>
                <tr>
                    <th scope="row">5</th>
                    <td>Максимальная частота</td>
                    <td>@Math.Round(Model.Product.MaximumFrequency, 2) Гц</td>
                </tr>
                <tr>
                    <th scope="row">6</th>
                    <td>Кэш L2 </td>
                    <td>@Model.Product.L2Cache МБ</td>
                </tr>
                <tr>
                    <th scope="row">7</th>
                    <td>Кэш L3</td>
                    <td>@Model.Product.L3Cache</td>
                </tr>
                <tr>
                    <th scope="row">8</th>
                    <td>Поддержка памяти</td>
                    <td>@Model.Product.MemorySupport</td>
                </tr>
                <tr>
                    <th scope="row">9</th>
                    <td>Количество каналов памяти</td>
                    <td>@Model.Product.NumberMemoryChannels</td>
                </tr>
                <tr>
                    <th scope="row">10</th>
                    <td>Максимальная частота памяти</td>
                    <td>@Math.Round(Model.Product.MaxMemoryFrequency, 2) Гц</td>
                </tr>
                <tr>
                    <th scope="row">11</th>
                    <td>Расчетная тепловая мощность </td>
                    <td>@Math.Round(Model.Product.Tdp, 2) Вт</td>
                </tr>
            </tbody>
        </table>

        <hr>

        <div class="row d-flex justify-content-center wow fadeIn">


            <div class="col-md-6 text-center">

                <h4 class="my-4 h4">Отзывы о товаре</h4>

            </div>


        </div>
        <hr>
        <div class="row d-flex justify-content-center wow fadeIn">


            <div class="text-center w-100">
                @if (User.Identity.IsAuthenticated)
                {
                    <h4 class="my-4 h4">Оставить отзыв</h4>
                    <form>
                        <div class="md-form amber-textarea active-amber-textarea">
                            <i class="fas fa-pencil-alt prefix"></i>
                            <textarea name="text" id="@Model.Product.Id" class="md-textarea form-control reviewText" rows="4"></textarea>
                            <label for="form22">Ваш текст</label>

                        </div>
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#reviewModel">
                            Отправить отзыв
                        </button>
                    </form>
                }
            </div>


        </div>

        <hr>
        <div class="card-comments mb-3 wow fadeIn">
            <div class="card-header font-weight-bold">@Model.Product.Product.GetCountReviews() comments</div>
            <div class="card-body">
                @foreach (var review in Model.Product.Product.Reviews)
                {
                    if (review.ReviewVerified)
                    {
                <div class="media d-block d-md-flex mt-4">
                    <img class="d-flex mb-3 mx-auto " style="width: 80px" src="@(review.User.UserImageUrl ?? "/userImages/user.png")" alt="Generic placeholder image">
                    <div class="media-body text-center text-md-left ml-md-3 ml-0">
                        <h5 class="mt-0 font-weight-bold">
                            @review.User.UserName
                            <a href="" class="pull-right">
                                <i class="fas fa-reply"></i>
                            </a>
                        </h5>
                        @review.Text
                    </div>
                </div>
                    }
                }
            </div>
        </div>

        <hr>

        <!--Grid row-->
        <div class="row d-flex justify-content-center wow fadeIn">

            <!--Grid column-->
            <div class="col-md-6 text-center">

                <h4 class="my-4 h4">Рекомендуемые товары</h4>

            </div>
            <!--Grid column-->

        </div>
        <section class="text-center mb-4">
            @foreach (var product in Model.PopularGoods)
            {
                <div class="card" style="width: 20%">

                    <!-- Card image -->
                    <img class="card-img-top" src="@product.Product.ImageUrl" alt="Card image cap">

                    <!-- Card content -->
                    <div class="card-body">

                        <!-- Title -->
                        <h6 class="card-title">
                            <a>@product.Product.Name</a>
                        </h6>

                        <!-- Text -->
                        <p class="card-text">
                            Кэш L2 уровня @product.L2Cache, кэш L3 уровня @product.L3Cache,
                            частота процессора: @product.MaximumFrequency,
                            производитель: @product.Product.Manufacturer.Name

                            <h4 class="font-weight-bold red-text">
                                <strong>
                                    @Math.Round(product.Product.Price, 2)$
                                </strong>
                            </h4>

                            @if (product.Product.IsAvailable())
                            {
                            <p>В наличии</p>
                        }
                        else
                        {
                            <p>Нет в наличии</p>
                        }
                            </p>
                            <p>
                                <a href="/Cpu/Info?id=@product.Product.Id">Подробнее...</a>
                            </p>
                            <a id="@product.Id" class="btn btn-red tocart">В корзину</a>
                        </div>
                    </div>
                }

        </section>
    </div>