WebApplication/ViewModels/ShoppingCartViewModel.cs
using System.Collections.Generic;
using Models.Order;

namespace WebApplication.ViewModels
{
    public class ShoppingCartViewModel
    {
        public List<CartItem> CartItems { get; set; }
        public decimal TotalPrice { get; set; }
        public int ItemsCount { get; set; }
    }
}

WebApplication/Controllers/OrderController.cs
using System;
using System.Linq;
using DataProvider.Interfaces;
using Logic.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Models.Order;
using Models.User;
using WebApplication.Extensions;
using WebApplication.Interfaces;
using WebApplication.ViewModels;

namespace WebApplication.Controllers
{
    public class OrderController : Controller
    {
        private const string CartSessionKey = "CartSessionKey";
        private readonly HttpContext _httpContext;
        private readonly IMailingSystem _mailingSystem;
        private readonly IOrderRepository _orderRepository;
        private readonly IRepositoryWrapper _repositoryWrapper;
        private readonly IShoppingCartService _shoppingCartService;
        private readonly UserManager<User> _userManager;
        private readonly IUserRepository _userRepository;

        public OrderController(IHttpContextAccessor httpContextAccessor, IRepositoryWrapper repositoryWrapper,
            IMailingSystem mailingSystem,
            UserManager<User> userManager, IShoppingCartService shoppingCartService)
        {
            _httpContext = httpContextAccessor.HttpContext;
            _repositoryWrapper = repositoryWrapper;
            _mailingSystem = mailingSystem;
            _userManager = userManager;
            _shoppingCartService = shoppingCartService;
            _orderRepository = _repositoryWrapper.OrderRepository;
            _userRepository = _repositoryWrapper.UserRepository;
        }

        [HttpPost]
        public IActionResult Add(OrderViewModel orderViewModel)
        {
            orderViewModel.Order.Id = Guid.NewGuid();
            orderViewModel.Order.Date = DateTime.Now;
            orderViewModel.Order.Customer.Id = Guid.NewGuid();
            orderViewModel.Order.Cart = _httpContext.Session.Get<Cart>(CartSessionKey);
            orderViewModel.Order.Cart.FinalPrice = orderViewModel.Order.Cart.GetFinalPrice();
            orderViewModel.Order.Status = OrderStatus.Processed;

            _mailingSystem.OrderMessage(orderViewModel.Order);

            foreach (var cartItem in orderViewModel.Order.Cart.CartItems) cartItem.Product = null;

            var user = _userManager.GetUserAsync(User);
            if (user.Result != null)
            {
                user.Result.Orders.Add(orderViewModel.Order);
                _userRepository.Update(user.Result);
            }


            _orderRepository.Create(orderViewModel.Order);
            _repositoryWrapper.Save();

            return View("SuccessfulOrder", orderViewModel.Order);
        }

        [HttpGet]
        public IActionResult Index()
        {
            var userId = _userManager.GetUserId(User);

            User user;

            if (userId != null)
                user = _userRepository
                           .FindByCondition(x => x.Id == userId)
                           .FirstOrDefault() ?? new User();
            else
                user = new User();


            var orderViewModel = new OrderViewModel
            {
                Order = new Order
                {
                    Cart = _httpContext.Session.Get<Cart>(CartSessionKey),
                    Customer = new Customer
                    {
                        Name = user.Name,
                        Surname = user.Surname,
                        Email = user.Email,
                        PhoneNumber = user.PhoneNumber,
                        Address = new Address
                        {
                            City = user.Address.City,
                            HouseOrFlat = user.Address.HouseOrFlat,
                            Region = user.Address.Region,
                            Street = user.Address.Street
                        }
                    }
                }
            };

            return View(orderViewModel);
        }

        [Authorize(Roles = "admin")]
        public IActionResult Table()
        {
            var orders = _orderRepository.FindAll().ToList();

            return View(orders);
        }
    }
}

WebApplication/Controllers/ShoppingCartController.cs
using System;
using System.Linq;
using DataProvider.Interfaces;
using Logic.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Models.Order;
using WebApplication.Extensions;
using WebApplication.ViewModels;

namespace WebApplication.Controllers
{
    public class ShoppingCartController : Controller
    {
        private const string CartSessionKey = "CartSessionKey";
        private readonly HttpContext _httpContext;

        private readonly IRepositoryWrapper _repositoryWrapper;
        private readonly IShoppingCartService _shoppingCartService;

        public ShoppingCartController(IRepositoryWrapper repositoryWrapper, IHttpContextAccessor httpContextAccessor,
            IShoppingCartService shoppingCartService)
        {
            _repositoryWrapper = repositoryWrapper;
            _shoppingCartService = shoppingCartService;
            _httpContext = httpContextAccessor.HttpContext;
            _shoppingCartService.Cart = GetCart();
        }

        public IActionResult Index()
        {
            var cart = _shoppingCartService.Cart;

            var shoppingCartViewModel = new ShoppingCartViewModel
            {
                CartItems = cart.CartItems.ToList(),
                ItemsCount = cart.GetTotalItemsCount(),
                TotalPrice = cart.GetFinalPrice()
            };

            return View(shoppingCartViewModel);
        }

        [HttpPost]
        public IActionResult AddToCart(Guid id)
        {
            var product = _repositoryWrapper.ProductRepository
                .FindByCondition(x => x.Id == id).FirstOrDefault();

            if (product != null)
                _shoppingCartService.AddItem(product, 1);

            SaveCart(_shoppingCartService.Cart);

            return Json(_shoppingCartService.Cart.GetTotalItemsCount());
        }

        public IActionResult DeleteProductFromLine(Guid id)
        {
            var product = _repositoryWrapper.ProductRepository
                .FindByCondition(x => x.Id == id).FirstOrDefault();

            if (product != null)
                _shoppingCartService.RemoveItem(product, 1);

            SaveCart(_shoppingCartService.Cart);

            return RedirectToAction("Index");
        }

        public IActionResult AddProductToLine(Guid id)
        {
            var product = _repositoryWrapper.ProductRepository
                .FindByCondition(x => x.Id == id).FirstOrDefault();

            if (product != null)
                _shoppingCartService.AddItem(product, 1);

            SaveCart(_shoppingCartService.Cart);

            return RedirectToAction("Index");
        }

        public IActionResult RemoveFromCart(Guid id)
        {
            var product = _repositoryWrapper.ProductRepository
                .FindByCondition(x => x.Id == id).FirstOrDefault();

            if (product != null)
                _shoppingCartService.RemoveLine(product);

            SaveCart(_shoppingCartService.Cart);

            return RedirectToAction("Index");
        }

        public IActionResult GetCountItems()
        {
            return Json( _shoppingCartService.Cart.GetTotalItemsCount());
        }

        private Cart GetCart()
        {
            var cart = _httpContext.Session.Get<Cart>(CartSessionKey);

            if (cart != null) return cart;

            cart = new Cart();
            _httpContext.Session.Set(CartSessionKey, cart);

            return cart;
        }

        private void SaveCart(Cart cart)
        {
            _httpContext.Session.Set(CartSessionKey, cart);
        }
    }
}

WebApplication/Views/ShoppingCart/Index.cshtml
@model WebApplication.ViewModels.ShoppingCartViewModel

@{
    ViewData["Title"] = "View";
    Layout = "_StartPage";
}
<style>
    @@media (max-device-width: 768px) {
        .mob-fix {
            height: auto !important;
            line-height: 20px !important;
            text-align: center;
        }
    }
</style>
<table class="table table">
    <thead>
    <tr>
        <th scope="col" class="w-20">Изображение</th>
        <th scope="col"class="w-20">Информация о товаре</th>
        <th scope="col"class="w-20">Количество</th>
        <th scope="col"class="w-20">Стоимость</th>
        <th scope="col"class="w-20">Удалить</th>
    </tr>
    </thead>
    <tbody>
        @foreach (var cartItem in Model.CartItems)
        {
        <tr>
            <td>
                <img src="@cartItem.Product.ImageUrl" alt="Card image cap" style="width: 250px; padding: 0; margin: 0;">
            </td>
            <td>
                <div class="card-body align-content-center">
                    <p>
                        <h6 class="card-title">
                            <a>@cartItem.Product.Name</a>
                        </h6>
                    <p class="card-text">

                        <h4 class="font-weight-bold red-text">
                        <strong>
                            @Math.Round(cartItem.Product.Price, 2)$
                        </strong>
                    </h4>
                    </p>
                    </p>
                </div>

            </td>
            <td>
                <div style="width: 150px">
                    <div class="col-lg-6 col-lg-offset-3">
                        <div class="input-group">
                            <form asp-controller="ShoppingCart" asp-action="DeleteProductFromLine" asp-route-id="@cartItem.Product.Id">
                                <span class="input-group-btn">
                                    <button id="minus" class="btn btn-danger" type="submit">-</button>
                                </span>
                            </form>
                            <input id="calc" type="text" class="form-control text-center" style="width: 80px" value="@cartItem.Quantity">
                            <form  asp-controller="ShoppingCart" asp-action="AddProductToLine" asp-route-id="@cartItem.Product.Id">
                                <span class="input-group-btn">
                                    <button id="plus" class="btn btn-success" type="submit">+</button>
                                </span>
                            </form>
                        </div>
                        </div>
          

                </div>
            </td>
            <td>
                <h4 class="font-weight-bold red-text">
                    <strong>
                        @Math.Round(cartItem.Product.Price * cartItem.Quantity, 2)$
                    </strong>
                </h4>
            </td>
            <td>
                <form asp-controller="ShoppingCart" asp-action="RemoveFromCart" asp-route-id="@cartItem.Product.Id">
                    <button type="submit" id="@cartItem.Product.Id" class="btn btn-red tocart">Удалить</button>
                </form>
            </td>

        </tr>
        }
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td><h4 class="font-weight-bold red-text">
            <strong>
                total:
                @Math.Round(Model.TotalPrice, 2)$
            </strong>
        </h4></td>
        <td>
            @if (Model.CartItems.Count > 0)
            {
                <a class="btn btn-blue tocart" asp-controller="Order" asp-action="Index">Оформить заказ</a>
            }

        </td>
    </tr>

    </tbody>
</table>